"""empty message

Revision ID: 0b2c7dd30baf
Revises: fdf055694a9a
Create Date: 2024-11-26 15:11:41.519167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b2c7dd30baf'
down_revision = 'fdf055694a9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referrer_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_referrals_referred_user_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_referrals_referred_user_id', 'users', ['referrer_id'], ['id'])
        batch_op.drop_column('referred_user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referrals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referred_user_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint('fk_referrals_referred_user_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_referrals_referred_user_id', 'users', ['referred_user_id'], ['id'])
        batch_op.drop_column('referrer_id')

    # ### end Alembic commands ###
