"""empty message

Revision ID: 783e1f7555bd
Revises: b5456e7901de
Create Date: 2024-11-27 12:24:19.230713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '783e1f7555bd'
down_revision = 'b5456e7901de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('pin', sa.String(length=4), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('pin')
        batch_op.drop_column('otp')

    # ### end Alembic commands ###
