"""empty message

Revision ID: bc1837ae22a6
Revises: c4bfe4d56270
Create Date: 2024-12-02 11:14:10.493503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc1837ae22a6'
down_revision = 'c4bfe4d56270'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_wallet_account_number', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('api_wallet_account_number')

    # ### end Alembic commands ###
