"""empty message

Revision ID: c4bfe4d56270
Revises: 5161ddeb2b59
Create Date: 2024-12-01 13:57:31.347879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4bfe4d56270'
down_revision = '5161ddeb2b59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_transaction_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cost_price', sa.Float(), nullable=False))
        batch_op.drop_column('transaction_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_wallet_id', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('api_wallet_id')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_id', sa.VARCHAR(length=80), nullable=False))
        batch_op.drop_column('cost_price')
        batch_op.drop_column('api_transaction_id')

    # ### end Alembic commands ###
